### ISSUE TITLE
pip can not detect the version number after the conda package is installed

### ISSUE THREAD

**Issue by wshanks** [conda-forge/platformdirs-feedstock#1]
I think this is essentially the same issue as discussed [here](https://github.com/platformdirs/platformdirs/discussions/32), but I have not had time to read through that discussion yet to what the conda packaging solution is. I ran into this issue trying to add platformdirs as a dependency of the pylint feedstock where I get this (see [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=366330&view=logs&j=516f237f-98f1-50a4-0946-c43fe5437b81&t=68e286c4-c87b-5a2e-10c4-f21f8bc51a62)):

```
+ pip check
pylint 2.10.2 has requirement platformdirs>=2.2.0, but you have platformdirs 0.0.0.
Tests failed for pylint-2.10.2-pyhd8ed1ab_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

**Comment by gaborbernat** [comment]
Perhaps https://github.com/conda-forge/platformdirs-feedstock/pull/2/files is all we need, per https://conda-forge.org/docs/maintainer/adding_pkgs.html#use-pip
