### ISSUE TITLE
Version on anaconda.org behind this repo

### ISSUE THREAD

**Issue by domdfcoding** [conda-forge/platformdirs-feedstock#6]
At https://anaconda.org/conda-forge/platformdirs, the current version is v2.3.0 (uploaded 5 months ago), but the version in the recipe in this repo is v2.4.1

I'm not sure how the packages are built and uploaded but I guess something has gone wrong somewhere.

**Comment by adament** [comment]
Thank you very much for reporting this. I am not sure what happened, but I will try forcing a rebuild and hopefully that fixes the issue.

**Comment by adament** [comment]
That seemed to do it.
